basic.forever(function () {
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 20)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 20)
    basic.pause(1000)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 50)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 0)
    basic.pause(1000)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 0)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 50)
    basic.pause(1000)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 20)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CCW, 20)
    basic.pause(1000)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 20)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CCW, 0)
    basic.pause(1000)
})
